src/clients/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from clients.views import UserRegisterView, UserProfileView, UserLoginView, EmailVerificationView

app_name = 'clients'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', UserRegisterView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='verification'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('', include('clients.urls', namespace='clients')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/clients/models.py
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    is_verified = models.BooleanField(default=False)


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def send_verification_email(self):
        link = reverse('clients:verification', kwargs={
            'email': self.user.email,
            'code': self.code
        })
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = 'ThreadFlix account verification'
        message = "Here's your verification link: {}".format(verification_link)
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return now() >= self.expiration

    def __str__(self):
        return f'EmailVerification {self.user}'

src/clients/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms import ImageField, FileInput

from clients.account_services import register_form_fields, login_form_fields, profile_form_fields_without_image
from clients.models import User
from clients.tasks import send_email


class UserLoginForm(AuthenticationForm):
    username, password = login_form_fields()

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(UserCreationForm):
    first_name, last_name, username, email, password1, password2 = register_form_fields()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=True)
        send_email.delay(user.id)
        return user


class UserProfileForm(UserChangeForm):
    first_name, last_name, username, email = profile_form_fields_without_image()
    image = ImageField(widget=FileInput(attrs={'class': 'custom-file-input'}), required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

src/clients/views.py
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView

from clients.account_services import email_verify
from clients.forms import UserLoginForm, UserRegisterForm, UserProfileForm
from clients.models import User
from default.views import TitleMixin


class UserLoginView(LoginView):
    template_name = 'clients/login.html'
    form_class = UserLoginForm


class UserRegisterView(SuccessMessageMixin, TitleMixin, CreateView):
    title = 'Sign up with ThreadFlix'
    model = User
    form_class = UserRegisterForm
    template_name = 'clients/registration.html'
    success_url = reverse_lazy('clients:login')
    success_message = 'Successful registration!'


class UserProfileView(TitleMixin, UpdateView):
    title = 'My profile'
    model = User
    form_class = UserProfileForm
    template_name = 'clients/profile.html'

    def get_success_url(self):
        return reverse('clients:profile', args=(self.object.id,))


class EmailVerificationView(TitleMixin, TemplateView):
    title = 'Email verification'
    template_name = 'clients/email_verification.html'

    def get(self, request, *args, **kwargs):
        get = super(EmailVerificationView, self).get(request, *args, **kwargs)
        return email_verify(kwargs=kwargs, if_true=get)

src/clients/templates/clients/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
    {% block content %} {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

src/clients/templates/clients/email_verification.html
{% extends 'clients/base.html' %}

{% block content %}
	<main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Congratulations</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>Your account has been successfully verified!</h4>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'clients:login' %}">Continue</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

src/clients/templates/clients/login.html
{% extends 'clients/base.html' %}
{% load socialaccount %}

{% block content%}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if messages or form.non_field_errors %}
                <div class="alert
                {% if messages %} alert-success {% else %} alert-warning {% endif %}
                alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;">
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% else %}
                        {{ form.non_field_errors }}
                    {% endif %} 

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Authorization</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'clients:login' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Username</label>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password.id_for_label }}">Password</label>
                                {{form.password}}
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="#">Forgot password?</a>
                                <input class="btn btn-primary" type="submit" value="Sign in">
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a href="#">
                                </a>
                                <a href="{% provider_login_url 'github' %}">
                                    <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                </a>
                                <a href="#">
                                </a>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'clients:registration' %}">New on ThreadFlix? Create an account!</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

src/clients/templates/clients/profile.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
	<link href="{% static 'vendor/css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
	<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Profile</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'clients:profile' user.id %}" method="post", enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">First name</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Last name</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Select an image</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Username</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Email</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Save">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            {% include 'products/carts.html' %}
        </div>
    </div>
</div>
{% endblock %}

src/clients/templates/clients/registration.html
{% extends 'clients/base.html' %}

{% block content%}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;">
                    {{ form.errors }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Create an account</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'clients:registration' %}" method="post">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Name</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Last name</label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Username</label>
                                    {{ form.username }}
                                </div>
                                <div class="col-md-6">
                                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Email</label>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password1.id_for_label }}">Password</label>
                                        {{ form.password1 }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password2.id_for_label }}">Confirm password</label>
                                        {{ form.password2 }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mt-4 mb-0">
                                <input class="btn btn-primary btn-block" type="submit" value="Create an account">
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'clients:login' %}">Already have an account? Sign in →</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}