src/clients/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from clients.views import UserRegisterView, UserProfileView, UserLoginView, EmailVerificationView

app_name = 'clients'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', UserRegisterView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='verification'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('', include('clients.urls', namespace='clients')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/urls.py
from django.urls import path

from orders.views import OrderCreateView

app_name = 'orders'

urlpatterns = [
    path('', OrderCreateView.as_view(), name='create'),

]

src/products/urls.py
from django.urls import path

from products.views import ProductsListView, add_to_cart, remove_from_cart

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>', ProductsListView.as_view(), name='category'),
    path('page/<int:page>', ProductsListView.as_view(), name='paginator'),
    path('carts/add/<int:product_id>/', add_to_cart, name='cart_add'),
    path('carts/remove/<int:cart_id>/', remove_from_cart, name='cart_remove'),
]

src/products/models.py
from django.db import models

from clients.models import User


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'Categories'


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    image = models.ImageField(upload_to='products_images')
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    def __str__(self):
        return f'Name: {self.name} | Category: {self.category.name}'


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'User: {self.user.username} | Product: {self.product.name}'

src/products/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, ListView

from default.views import TitleMixin
from .models import Category, Product, Cart


class IndexView(TitleMixin, TemplateView):
    title = 'ThreadFlix'
    template_name = 'products/index.html'


class ProductsListView(TitleMixin, ListView):
    title = 'ThreadFlix catalogue'
    model = Product
    template_name = 'products/products.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        queryset = queryset.filter(category_id=category_id) if category_id else queryset
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data()

        categories = cache.get('categories')
        if not categories:
            cache_time = 60  # seconds
            categories_queryset = Category.objects.all().order_by('id')
            context['categories'] = categories_queryset
            cache.set('categories', context['categories'], cache_time)
        else:
            context['categories'] = categories
        return context


@login_required
def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    carts = Cart.objects.filter(user=request.user, product=product)

    if not carts.exists():
        Cart.objects.create(user=request.user, product=product, quantity=1)
    else:
        cart = carts.first()
        cart.quantity += 1
        cart.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def remove_from_cart(request, cart_id):
    cart = Cart.objects.get(id=cart_id)
    cart.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

src/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">ThreadFlix</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Catalogue <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'clients:profile' user.id %}">My profile</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'orders:create' %}">Orders</a></li>
                        {% if user.is_superuser or user.is_staff %}
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin-panel</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'clients:logout' %}">
                                Log out
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'clients:login' %}">Sign in <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

src/products/templates/products/carts.html
{% load humanize %}
{% if carts %}
<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
    Cart <span class="badge badge-secondary badge-pill">{{carts.count}}</span>
</h4>
{% for cart in carts %}
    <div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ cart.product.name }}</h5>
        <p class="card-text">{{ cart.product.description }}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item bg-light">
            <div class="row text-center">
                <div class="col-lg-4">
                    <input name="basketID" type="number" class="form-control"
                           value="{{ cart.quantity }}" min="0">
                </div>
                <div class="col-lg-4">{{ cart.total|intcomma }}₴</div>
                <div class="col-lg-4">
                    <a href="{% url 'products:cart_remove' cart.id %}">
                        <i class="fas fa-trash"></i>
                    </a>
                </div>
            </div>
        </li>
    </ul>
</div>
{% endfor %}
<div class="card mb-3">
    <div class="card-footer">
        <p class="float-left">Total</p>
        <h4 class="float-right">{{total|intcomma}}₴</h4>
    </div>
</div>
<a class="btn btn-success btn-lg float-right" href="{% url 'orders:create' %}">
    Buy
</a>
{% else %}
<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
    Cart is empty
</h4>
{% endif %}

src/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">ThreadFlix</h1>
                <p>
                    Welcome to our virtual fashion haven, where trends come to life and your style dreams soar!
                    Step into a world of sartorial splendor, where every click reveals a captivating collection handpicked to elevate your wardrobe to new heights.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Explore
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

src/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static cache humanize %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">ThreadFlix</h1>
            <div class="list-group">
            {% for category in categories %}
                <a href="{% url 'products:category' category.id  %}" class="list-group-item">{{category.name}}</a>
            {% endfor %}
            </div>

        </div>

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
            {% cache 60 object_list %}
            {% for product in object_list %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src='{{product.image.url}}'
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price|intcomma}}₴</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'products:cart_add' product.id %}">Add to cart</a>

                        </div>
                    </div>
                </div>
            {% endfor %}
            {% endcache %}

            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="{% if page_obj.has_previous %} {% url 'products:paginator' page_obj.previous_page_number %}
                        {% else %} # {% endif %}" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    {% for page in paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="{% url 'products:paginator' page %}">{{ page }}</a></li>
                    {% endfor %}

                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link" href="{% if page_obj.has_next %} {% url 'products:paginator' page_obj.next_page_number %}
                        {% else %} # {% endif %}">Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
{% endblock %}

{% block footer%}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; ThreadFlix 2023</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}